FROM node:20-bookworm-slim

WORKDIR /workspace

COPY package*.json ./
COPY apps/web/package*.json ./apps/web/
COPY packages/shared-types/package*.json ./packages/shared-types/

RUN npm install

EXPOSE 4200
